name: localhost_scan

on: 
  pull_request:
    branches: 
      -main
  push:
    branches: 
      -main

  workflow_dispatch:
  
permissions: 
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v2
      - name: create directory
        run: mkdir ${{ github.workspace }}/output_fold
      - name: change directory owner
        run:  sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v2.3.0
        env:
          CX_APIKEY: ${{secrets.CX_APIKEY}}
        with:
          command: web
          config: ./localhost_config.yaml
          base_url: http://ind.ast.checkmarx.net
          environment_id: 83c1c65d-db18-475c-a1a6-1fe068b38020
          output: ${{ github.workspace }}/output_fold
      - name: reclaim output directory
        if: always()
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_fold
      - uses: actions/upload-artifact@v3
        if: always()
        name: Upload Logs
        with:
          name: report
          path: ${{ github.workspace }}/output_fold
        
