name: Checkmarx DAST Pipeline

on: 
  # No trigger here, this pipeline will not run automatically.
  # You can add a manual trigger like the following if needed:
   workflow_dispatch:

jobs:
  checkmarx-dast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkmarx DAST Github Action
      uses: Checkmarx/dast-github-action@v2.3.0
      with:
        # The type of scan to perform (web, api)
        command: web
        # The path to the ZAP configuration file
        config: ./gin_juice.yaml
        # The base URL for the Checkmarx One Servers
        base_url: https://ind.ast.checkmarx.net
        # The environment ID previously created in the Frontend
        environment_id: bd462e37-c712-440a-9e0c-7984b09d5252
        # The path to generate the output (optional)
        output: ./checkmarx_output
        # The log level for the logs (optional, default is info)
        log_level: debug
        # Set to true in order to print the logs to stdout (optional, default is false)
        verbose: true
        
