name: Checkmarx SCA Scan (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sca-scan:
    name: Download and Extract CxSCA Resolver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download and extract CxSCA Resolver (Windows)
        run: |
          curl -L -o ScaResolver-glibc64.tar.gz https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-glibc64.tar.gz
          tar -xzf ScaResolver-glibc64.tar.gz
          chmod +x ScaResolver
          ./ScaResolver --help

      # Upload the ScaResolver folder as an artifact to use in the next job
      - name: Upload CxSCA Resolver as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ScaResolver
          path: ./ScaResolver

  ast-scan:
    name: Run Checkmarx AST Scan
    runs-on: ubuntu-latest
    needs: sca-scan  # This makes the ast-scan job dependent on the completion of sca-scan job

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Download the ScaResolver artifact from the previous job
      - name: Download CxSCA Resolver artifact
        uses: actions/download-artifact@v3
        with:
          name: ScaResolver

      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          base_uri: https://eu.ast.checkmarx.net
          cx_tenant: ast_abdul_ansari3
          cx_client_id: dhruv-lts
          cx_client_secret: a7JMTAwqqu56bHgS9JLmqWrw7jqdshf5
          additional_params: '--sca-resolver ./ScaResolver'
